test4

diff --git a/.github/workflows/cleanup-tags.yml b/.github/workflows/cleanup-tags.yml
--- a/.github/workflows/cleanup-tags.yml
+++ b/.github/workflows/cleanup-tags.yml
@@ -25,10 +25,12 @@ jobs:
           START_TAG=12
           END_TAG=33
           for i in $(seq $START_TAG $END_TAG); do
-            TAG="v4.$i.0"
-            echo "Deleting tag $TAG"
-            git tag -d "$TAG" || echo "Tag $TAG not found locally."
-            git push origin :refs/tags/$TAG || echo "Tag $TAG not found remotely."
+            for j in $(seq 0 10); do
+              TAG="v4.$i.$j"
+              echo "Deleting tag $TAG"
+              git tag -d "$TAG" || echo "Tag $TAG not found locally."
+              git push origin :refs/tags/$TAG || echo "Tag $TAG not found remotely."
+            done
           done
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
